

<?php include 'main.php'?>

<div class="Contack">
   <h2>Contack Us</h2>
   <p align="justify"><img src="images/c2.jpg" width="200" height="100" align="left" hspace="10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget rhoncus risus, et dictum eros. Curabitur pellentesque, eros non gravida pharetra, quam lectus commodo nunc, in lacinia nulla ligula id diam. Suspendisse lobortis, orci ac fermentum mollis, orci ex varius elit, non facilisis urna lectus eu velit. Cras eu tortor quam. Maecenas eu magna sit amet mauris placerat malesuada. Fusce id dolor velit. Mauris in metus odio.fringilla magna. In lorem diam, bibendum et sapien nec, sagittis varius arcu. Donec porttitor euismod felis, non dignissim magna dignissim vitae. Aliquam at eros et risus laoreet ultricies nec a velit. Mauris sodales eros diam, vel maximus enim malesuada eget. Cras eu sapien malesuada, aliquet tellus ut, semper mauris. In hac habitasse platea dictumst. Nulla facilisifringilla magna. In lorem diam, bibendum et sapien nec, sagittis varius arcu. Donec porttitor euismod felis, non dignissim magna dignissim vitae. Aliquam at eros et risus laoreet ultricies nec a velit. Mauris sodales eros diam, vel maximus enim malesuada eget. Cras eu sapien malesuada, aliquet tellus ut, semper mauris. In hac habitasse platea dictumst. Nulla facilisi </p>
   <br>
   <p align="justify">Sed at viverra magna. Nam ut enim tristique, mollis velit quis, semper odio. Curabitur iaculis felis non leo tristique dictum. Nunc eu nulla dignissim, fringilla tellus pretium, fringilla magna. In lorem diam, bibendum et sapien nec, sagittis varius arcu. Donec porttitor euismod felis, non dignissim magna dignissim vitae. Aliquam at eros et risus laoreet ultricies nec a velit. Mauris sodales eros diam, vel maximus enim malesuada eget. Cras eu sapien malesuada, aliquet tellus ut, semper mauris. In hac habitasse platea dictumst. Nulla facilisi. </p>

  <br>
   <p align="justify">Etiam dapibus eget sem eu lobortis. Vestibulum interdum quam massa, vehicula cursus mauris dictum vitae. Vestibulum aliquet nisl erat, ut facilisis orci commodo et. Phasellus euismod turpis et nisl interdum, sit amet ullamcorper turpis vestibulum. Nullam faucibus neque ut gravida consequat. Morbi pellentesque nibh elit, id lacinia eros finibus et. Proin non elit nec ipsum commodo interdum.fringilla magna. In lorem diam, bibendum et sapien nec, sagittis varius arcu. Donec porttitor euismod felis, non dignissim magna dignissim vitae. Aliquam at eros et risus laoreet ultricies nec a velit. Mauris sodales eros diam, vel maximus enim malesuada eget. Cras eu sapien malesuada, aliquet tellus ut, semper mauris. In hac habitasse platea dictumst. Nulla facilisi fringilla magna. In lorem diam, bibendum et sapien nec, sagittis varius arcu. Donec porttitor euismod felis, non dignissim magna dignissim vitae. Aliquam at eros et risus laoreet ultricies nec a velit. Mauris sodales eros diam, vel maximus enim malesuada eget. Cras eu sapien malesuada, aliquet tellus ut, semper mauris. In hac habitasse platea dictumst. Nulla facilisi </p>
   <br><br>
   <p align="justify">Etiam dapibus eget sem eu lobortis. Vestibulum interdum quam massa, vehicula cursus mauris dictum vitae. Vestibulum aliquet nisl erat, ut facilisis orci commodo et. Phasellus euismod turpis et nisl interdum, sit amet ullamcorper turpis vestibulum. Nullam faucibus neque ut gravida consequat. Morbi pellentesque nibh elit, id lacinia eros finibus et. Proin non elit nec ipsum commodo interdum. </p>

</div>
<?php include 'footer.php'?>